"""empty message

Revision ID: 4b8e4d8e1281
Revises: 86e95c6ce6ec
Create Date: 2023-11-02 14:38:14.639028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8e4d8e1281'
down_revision = '86e95c6ce6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('code_table', schema=None) as batch_op:
        batch_op.drop_column('pic')

    # ### end Alembic commands ###
