"""empty message

Revision ID: 71588f36ac08
Revises: 
Create Date: 2023-10-26 11:22:03.091669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71588f36ac08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('html', sa.String(), nullable=True),
    sa.Column('css', sa.String(), nullable=True),
    sa.Column('js', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follow_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('following_user', sa.Integer(), nullable=True),
    sa.Column('followed_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_user'], ['user_table.id'], name=op.f('fk_follow_table_followed_user_user_table')),
    sa.ForeignKeyConstraint(['following_user'], ['user_table.id'], name=op.f('fk_follow_table_following_user_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code_table.id'], name=op.f('fk_room_table_code_id_code_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_room_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_code_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code_table.id'], name=op.f('fk_user_code_table_code_id_code_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_user_code_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_code_table')
    op.drop_table('room_table')
    op.drop_table('follow_table')
    op.drop_table('user_table')
    op.drop_table('code_table')
    # ### end Alembic commands ###
